### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [vincentdnl/zsh-crypto-prices#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by vincentdnl** [comment]
Thank you, I just did add a MIT License file!

**Comment by unixorn** [comment]
Thanks!
